name: face_extractor
description: "A flutter project which can be used to extract faces using Yunet model"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  opencv_dart: ^1.4.3
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

hooks:
  user_defines:
    dartcv4:
      exclude_modules:
        - features2d
        - contrib
        - videoio
        - imgproc
        - highgui
        - imgcodecs
        - videoio
        - calib3d
      include_modules:
        - imgproc
        - dnn

